# Generated by Django 5.1.6 on 2025-03-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
