# Generated by Django 5.1.6 on 2025-03-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_faq_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='course',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='faq',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
