# Generated by Django 5.1.6 on 2025-04-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dean_managers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerprofile',
            name='role',
            field=models.CharField(default='dean manager', max_length=20),
        ),
    ]
