# Generated by Django 5.1.6 on 2025-03-15 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('kbtu_id', models.CharField(default='21B000000', max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('school', models.CharField(default='SITE', max_length=50)),
                ('speciality', models.CharField(default='IS', max_length=50)),
                ('course', models.IntegerField(default=4)),
                ('telephone_number', models.CharField(default='87777777777', max_length=20)),
                ('role', models.CharField(default='student', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
