# Generated by Django 5.1.6 on 2025-04-06 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_samples', '0002_documentsample'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationletter',
            name='course',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitationletter',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invitationletter',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invitationletter',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invitationletter',
            name='speciality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invitationletter',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.studentprofile'),
        ),
    ]
